### ISSUE TITLE
Change to lein-yagni

### ISSUE THREAD

**Issue by bostonaholic** [venantius/yagni#20]
It seems like there is a convention of naming leiningen plugins `lein-*`.

https://github.com/technomancy/leiningen/wiki/Plugin

Maybe consider a "rebranding" for the next `0.X.0` release?

**Comment by venantius** [comment]
I've gone back and forth over this in the past. Historically I've modeled my Leiningen plugins after Eastwood's directory structure (i.e.., single project, single src tree, src is split into /$plugin_name and /leiningen). I'm also not sure there's that much value in adhering to this sort of naming convention. 

On the other hand, I don't have a good argument against it, either. I'll noodle on it.

**Comment by bostonaholic** [comment]
Cleaning up my GitHub environment. Feel free to reopen if necessary.
