### ISSUE TITLE
Log4J incompatibility

### ISSUE THREAD

**Issue by lgrapenthin** [venantius/yagni#29]
With Datomic Pro on the classpath, I get Detected both log4j-over-slf4j.jar AND slf4j-log4j12.jar on the class path, preempting StackOverflowError. See also http://www.slf4j.org/codes.html#log4jDelegationLoop for more details.

[venantius/yagni "0.1.2"
             :exclusions [org.slf4j/slf4j-log4j12]
             ]

in profiles doesn't cut it.

**Comment by venantius** [comment]
Yep, sorry about that - should have removed the dependency when I removed the associated configuration. Will mark this for the `0.1.3` release.

**Comment by venantius** [comment]
Resolved as of https://github.com/venantius/yagni/commit/2735cc850ba15716dfb6666bc34fcc9a274827e5
